[build]
  functions = "netlify/functions"
  publish = "."

# -------------------------------
# 代理计数服务 (Counter.dev)
# -------------------------------

# 脚本文件代理
[[redirects]]
  from = "/counter/script.js"
  to = "https://cdn.counter.dev/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/counter/track"
  to = "https://t.counter.dev/track"
  status = 200
  force = true
  query = { * = "*" }

[[redirects]]
  from = "/counter/trackpage"
  to = "https://t.counter.dev/trackpage"
  status = 200
  force = true
  query = { * = "*" }

